rabbit_a:
  image: liyustar/rabbitmq-sshd
  hostname: rabbit_a
  ports:
   - "10022:22"
   - "5672:5672"
   - "15672:15672"

rabbit_b:
  image: liyustar/rabbitmq-sshd
  hostname: rabbit_b
  links:
   - rabbit_a
  environment:
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit_a
   - RAM_NODE=true
  ports:
   - "10023:22"
   - "5673:5672"
   - "15673:15672"

rabbit_c:
  image: liyustar/rabbitmq-sshd
  hostname: rabbit_c
  links:
   - rabbit_a
   - rabbit_b
  environment:
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit_a
  ports:
   - "10024:22"
   - "5674:5672"
   - "15674:15672"

haproxy:
  image: liyustar/haproxy
  hostname: haproxy
  links:
   - rabbit_a
   - rabbit_b
   - rabbit_c
  ports:
   - "10025:22"
   - "5675:5672"
   - "8888:8888"
